### ISSUE TITLE
resources/service.rb missing from 0.6.0 cookbook release

### ISSUE THREAD

**Issue by sentience** [hamann/eye-chef-cookbook#4]
When berkshelf downloads the current version 0.6.0 of this cookbook, the `resources/service.rb` file is missing. This causes my Chef runs to fail because `eye_service` is not defined.

You can reproduce this by downloading the current release from the Chef Supermarket: https://supermarket.getchef.com/cookbooks/eye/download

Extract the Tar file and observe that there is no `resources` directory inside it.

**Comment by hamann** [comment]
Thanks!
That's a bug in the stove version I've used. Please try 0.6.1

**Comment by sentience** [comment]
All good with 0.6.1. Thanks!
