### ISSUE TITLE
0.7.3 Version on Supermarket is missing part of the LWRP

### ISSUE THREAD

**Issue by martinisoft** [hamann/eye-chef-cookbook#6]
This may have been a mistake with the release, but the 0.7.3 version of the cookbook uploaded to the supermarket is missing the resources folder, which is preventing the cookbook from converging correctly.

**Comment by hamann** [comment]
Thanks for reporting. 0.7.4 is uploaded to supermarket

**Comment by martinisoft** [comment]
Welcome @hamann thank you for making a nice cookbook for eye! You'll probably see more reports from me as I start using this in production.
