### ISSUE TITLE
If a system ruby is not installed, eye service will not work or start

### ISSUE THREAD

**Issue by martinisoft** [hamann/eye-chef-cookbook#7]
Right now if you use the eye cookbook out of the box with nothing else, the attributes for the eye binary will default to the embedded chef ruby, this results in the service not being able to start because it has an incorrect path to where the eye binary gets installed. Typically on a system installation this is `/usr/bin/ruby` instead of `/opt/chef/embedded/bin/ruby`

**Comment by hamann** [comment]
You're right. But what's the best way to handle that?
Our solution for eye (and for all other gems which should be installed global) is to install ruby at compile time and reload ohai, like

``` ruby
package 'ruby' do
  package_name node[:ruby][:package_name]
  version node[:ruby][:version]
  action :nothing
end.run_action(:install)

ohai "reload_ruby" do
  plugin 'languages/ruby'
  action :nothing
end.run_action(:reload)
```

Than eye will be installed with system's ruby instead of embedded chef ruby.

Do you have a better idea?
